# Generated by Django 6.0 on 2026-01-02 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_answers',
            field=models.JSONField(default=dict, help_text="e.g. {'answer': 'B'}"),
        ),
    ]
